import json
import os
import tempfile
from dataclasses import dataclass
from typing import Any

from interpretation.template_manager.student_data_sheet_template import StudentDataSheetTemplate
from interpretation.template_manager.storage.serialization import serialize, deserialize
from interpretation.templates.student_data_sheet_interpreter import SessionDataSectionInterpreterBase

FORMAT_VERSION: int = 2


@dataclass
class TemplateCreateDto:
    """
    Data Transfer Object for creating new templates.

    Does not include ID as it will be generated by the store.
    """

    name: str
    configured_interpreters: list[SessionDataSectionInterpreterBase]
    description: str = ""


@dataclass
class TemplateEditDto:
    """
    Data Transfer Object for editing existing templates.

    Does not include ID as it should remain unchanged during edits.
    """

    name: str
    configured_interpreters: list[SessionDataSectionInterpreterBase]
    description: str = ""


class UnreadableTemplatesError(Exception):
    """The templates file exists but cannot be read."""

    def __init__(self, file_path: str, reason: str) -> None:
        super().__init__(f"Could not read templates from {file_path}: {reason}")
        self.file_path: str = file_path


class TemplateStore:
    """
    Repository for managing Student Data Sheet Templates, kept in a local JSON file.

    The file is read on every call. Writes go to a temporary file that then replaces the
    real one, so a failed save never leaves a half-written file. A file the store cannot
    read is never written over.

    File format 2 is an object holding `format_version`, `last_template_id` (the highest
    template id ever given out, so ids are never reused) and `templates`. A bare list of
    templates is format 1, from before format 2 existed, and is still read.
    """

    def __init__(self, storage_file_path: str) -> None:
        """Initialize the template store with file-based storage. No file is read or created until it is used.

        Args:
            storage_file_path: Path to the JSON file for storing templates
        """
        self.storage_file_path: str = storage_file_path

    def create_empty_file(self) -> None:
        """
        Create the templates file holding no Templates, in format 2.

        `last_template_id` starts at 0 only here, for a brand new file, so ids are never
        given out again against Students who still point at older templates. The file is
        opened in exclusive-create mode, so an existing file is never written over.

        Raises:
            FileExistsError: The file already exists; it is left unchanged
            OSError: The file could not be written; any partial file is removed
        """
        data = {'format_version': FORMAT_VERSION, 'last_template_id': 0, 'templates': []}
        with open(self.storage_file_path, 'x', encoding='utf-8') as file:
            try:
                json.dump(data, file, indent=2, ensure_ascii=False)
            except BaseException:
                file.close()
                _remove_quietly(self.storage_file_path)
                raise

    def check_readable(self) -> None:
        """
        Check that the templates file can be read.

        A missing file is fine, because the store treats it as empty. The read methods
        turn an unreadable file into an empty list, so callers that must tell the two
        apart call this first.

        Raises:
            UnreadableTemplatesError: If the file exists but is not a readable templates file
        """
        self._load()

    def get_all_templates(self) -> list[StudentDataSheetTemplate]:
        """
        Retrieve all available templates from file storage.

        Returns:
            Every saved template, in saved order. Empty if the file is missing or unreadable.
        """
        return [self._convert_data_to_template(template_data) for template_data in self._load_entries_or_empty()]

    def get_template_by_id(self, template_id: str) -> StudentDataSheetTemplate | None:
        """
        Retrieve a template by its ID from file storage.

        Args:
            template_id: The ID of the template to retrieve

        Returns:
            The template if found, None otherwise (including when the file is unreadable)
        """
        for template_data in self._load_entries_or_empty():
            if template_data['id'] == template_id:
                return self._convert_data_to_template(template_data)
        return None

    def create_template(self, create_dto: TemplateCreateDto) -> StudentDataSheetTemplate:
        """
        Create a new template from a DTO and save to file.

        Args:
            create_dto: The data for the new template

        Returns:
            The created template with generated ID

        Raises:
            UnreadableTemplatesError: If the file cannot be read; nothing is written
            OSError: If the file cannot be saved; the old file is unchanged
        """
        templates_data, last_template_id = self._load()
        new_id = self._next_id(templates_data, last_template_id)

        new_template = StudentDataSheetTemplate(
            new_id,
            create_dto.name,
            create_dto.configured_interpreters,
            create_dto.description,
        )
        templates_data.append(self._convert_template_to_data(new_template))

        self._save(templates_data, int(new_id))
        return new_template

    def edit_template(self, template_id: str, edit_dto: TemplateEditDto) -> StudentDataSheetTemplate | None:
        """
        Edit an existing template using a DTO and save to file. The template keeps its ID
        and its position in the file.

        Args:
            template_id: The ID of the template to edit
            edit_dto: The new data for the template

        Returns:
            The updated template if found, None if not found (nothing is written)

        Raises:
            UnreadableTemplatesError: If the file cannot be read; nothing is written
            OSError: If the file cannot be saved; the old file is unchanged
        """
        templates_data, last_template_id = self._load()

        for i, template_data in enumerate(templates_data):
            if template_data['id'] == template_id:
                updated_template = StudentDataSheetTemplate(
                    template_id,  # Keep the same ID
                    edit_dto.name,
                    edit_dto.configured_interpreters,
                    edit_dto.description,
                )
                templates_data[i] = self._convert_template_to_data(updated_template)
                self._save(templates_data, last_template_id)
                return updated_template

        # Template not found
        return None

    def delete_template(self, template_id: str) -> bool:
        """
        Delete a template by its ID from file storage. Its ID is never given out again.

        Args:
            template_id: The ID of the template to delete

        Returns:
            True if template was found and deleted, False otherwise

        Raises:
            UnreadableTemplatesError: If the file cannot be read; nothing is written
            OSError: If the file cannot be saved; the old file is unchanged
        """
        templates_data, last_template_id = self._load()

        for i, template_data in enumerate(templates_data):
            if template_data['id'] == template_id:
                del templates_data[i]
                self._save(templates_data, last_template_id)
                return True
        return False

    def generate_new_id(self) -> str:
        """
        Generate a new unique ID for a template. It is never an ID given out before, even
        one whose template has since been deleted.

        Returns:
            A new unique ID

        Raises:
            UnreadableTemplatesError: If the file cannot be read
        """
        templates_data, last_template_id = self._load()
        return self._next_id(templates_data, last_template_id)

    def _next_id(self, templates_data: list[dict[str, Any]], last_template_id: int) -> str:
        """Return one more than the highest ID ever given out or present in the file."""
        return str(max(last_template_id, _highest_numeric_id(templates_data)) + 1)

    def _convert_data_to_template(self, template_data: dict[str, Any]) -> StudentDataSheetTemplate:
        """
        Convert a template data dictionary to a StudentDataSheetTemplate object.

        Args:
            template_data: Dictionary containing template data

        Returns:
            The converted template object. A missing description loads as "".
        """
        interpreters = [deserialize(interpreter_data) for interpreter_data in template_data['interpreters']]
        return StudentDataSheetTemplate(
            template_data['id'],
            template_data['name'],
            interpreters,
            template_data.get('description', ''),
        )

    def _convert_template_to_data(self, template: StudentDataSheetTemplate) -> dict[str, Any]:
        """Convert a template to the dictionary saved in the file."""
        return {
            'id': template.id,
            'name': template.name,
            'description': template.description,
            'interpreters': [serialize(interpreter) for interpreter in template.interpreters],
        }

    def _load_entries_or_empty(self) -> list[dict[str, Any]]:
        """Return the saved template entries, or an empty list if the file cannot be read."""
        try:
            templates_data, _ = self._load()
        except UnreadableTemplatesError:
            return []
        return templates_data

    def _load(self) -> tuple[list[dict[str, Any]], int]:
        """
        Read the template entries and the highest ID ever given out. A missing file means
        no templates.

        Raises:
            UnreadableTemplatesError: If the file is not valid JSON, is not in a known
                format, or was written by a newer version of the app
        """
        if not os.path.exists(self.storage_file_path):
            return [], 0
        try:
            with open(self.storage_file_path, 'r', encoding='utf-8') as file:
                data = json.load(file)
        except (OSError, json.JSONDecodeError, UnicodeDecodeError) as e:
            raise UnreadableTemplatesError(self.storage_file_path, str(e)) from e

        # Format 1: a bare list of templates.
        if isinstance(data, list):
            return data, _highest_numeric_id(data)

        if not isinstance(data, dict) or not isinstance(data.get('templates'), list):
            raise UnreadableTemplatesError(self.storage_file_path, "not in the expected format")
        format_version = data.get('format_version')
        if not isinstance(format_version, int) or isinstance(format_version, bool):
            raise UnreadableTemplatesError(self.storage_file_path, "invalid format_version")
        if format_version > FORMAT_VERSION:
            raise UnreadableTemplatesError(self.storage_file_path, "written by a newer version of the app")

        templates_data = data['templates']
        last_template_id = data.get('last_template_id')
        if not isinstance(last_template_id, int) or isinstance(last_template_id, bool):
            last_template_id = _highest_numeric_id(templates_data)
        return templates_data, last_template_id

    def _save(self, templates_data: list[dict[str, Any]], last_template_id: int) -> None:
        """
        Write every template to the file in format 2, replacing it in one step.
        Creates parent directories if they don't exist.

        Raises:
            OSError: If the file cannot be written; the old file is unchanged
        """
        data = {
            'format_version': FORMAT_VERSION,
            'last_template_id': last_template_id,
            'templates': templates_data,
        }
        directory = os.path.dirname(os.path.abspath(self.storage_file_path))
        os.makedirs(directory, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            'w', encoding='utf-8', dir=directory, suffix='.tmp', delete=False
        ) as file:
            temp_path = file.name
        try:
            with open(temp_path, 'w', encoding='utf-8') as file:
                json.dump(data, file, indent=2, ensure_ascii=True)
            os.replace(temp_path, self.storage_file_path)
        except BaseException:
            # Leave no temporary file behind when the save fails
            if os.path.exists(temp_path):
                os.unlink(temp_path)
            raise


def _highest_numeric_id(templates_data: list[dict[str, Any]]) -> int:
    """Return the highest numeric template ID in the entries, or 0 if there are none."""
    highest = 0
    for template_data in templates_data:
        try:
            highest = max(highest, int(template_data['id']))
        except (KeyError, TypeError, ValueError):
            # Non-numeric ID, skip
            pass
    return highest


def _remove_quietly(path: str) -> None:
    """Remove a partly written file, ignoring a failure to remove it."""
    try:
        os.remove(path)
    except OSError:
        pass
