import json
import os
from interpretation.template_manager.student_data_sheet_template import StudentDataSheetTemplate


class TemplateCreateDto:
    """
    Data Transfer Object for creating new templates.
    
    Does not include ID as it will be generated by the store.
    """
    
    def __init__(self, name, file_location, configured_interpreters):
        """
        Initialize the create DTO.
        
        Args:
            name (str): The name of the template
            file_location (str): The file location of the template
            configured_interpreters: The configured interpreter object
        """
        self.name = name
        self.file_location = file_location
        self.configured_interpreters = configured_interpreters


class TemplateEditDto:
    """
    Data Transfer Object for editing existing templates.
    
    Does not include ID as it should remain unchanged during edits.
    """
    
    def __init__(self, name, file_location, configured_interpreters):
        """
        Initialize the edit DTO.
        
        Args:
            name (str): The name of the template
            file_location (str): The file location of the template
            configured_interpreters: The configured interpreter object
        """
        self.name = name
        self.file_location = file_location
        self.configured_interpreters = configured_interpreters


class TemplateStore:
    """
    Repository for managing Student Data Sheet Templates.

    This is a stub implementation that keeps templates in RAM.
    In a real implementation, this would handle persistence to files,
    databases, or other storage mechanisms.
    """

    def __init__(self, storage_file_path):
        """Initialize the template store with file-based storage.
        
        Args:
            storage_file_path (str): Path to the JSON file for storing templates
        """
        self.storage_file_path = storage_file_path
        self._ensure_storage_file_exists()

    def get_all_templates(self):
        """
        Retrieve all available templates from file storage.

        Returns:
            list: List of StudentDataSheetTemplate objects
        """
        templates_data = self._load_templates_from_file()
        templates = []
        for template_data in templates_data:
            template = self._convert_data_to_template(template_data)
            templates.append(template)
        return templates

    def get_template_by_id(self, template_id):
        """
        Retrieve a template by its ID from file storage.

        Args:
            template_id (str): The ID of the template to retrieve

        Returns:
            StudentDataSheetTemplate or None: The template if found, None otherwise
        """
        templates_data = self._load_templates_from_file()
        for template_data in templates_data:
            if template_data['id'] == template_id:
                return self._convert_data_to_template(template_data)
        return None

    def create_template(self, create_dto):
        """
        Create a new template from a DTO and save to file.

        Args:
            create_dto (TemplateCreateDto): The data for the new template

        Returns:
            StudentDataSheetTemplate: The created template with generated ID
        """
        # Generate a new unique ID
        new_id = self.generate_new_id()
        
        # Create the template object
        new_template = StudentDataSheetTemplate(
            new_id,
            create_dto.name,
            create_dto.file_location,
            create_dto.configured_interpreters
        )
        
        # Load existing templates and add the new one
        templates_data = self._load_templates_from_file()
        new_template_data = {
            'id': new_template.id,
            'name': new_template.name,
            'file_location': new_template.file_location,
            'interpreters': new_template.interpreters # Use the serialization.py stuff for this.
        }
        templates_data.append(new_template_data)
        
        # Save updated list to file
        self._save_templates_to_file(templates_data)
        
        return new_template
        
    def edit_template(self, template_id, edit_dto):
        """
        Edit an existing template using a DTO and save to file.

        Args:
            template_id (str): The ID of the template to edit
            edit_dto (TemplateEditDto): The new data for the template

        Returns:
            StudentDataSheetTemplate or None: The updated template if found, None if not found
        """
        # Load templates from file
        templates_data = self._load_templates_from_file()
        
        # Find the template to edit
        for i, template_data in enumerate(templates_data):
            if template_data['id'] == template_id:
                # Create updated template with same ID
                updated_template = StudentDataSheetTemplate(
                    template_id,  # Keep the same ID
                    edit_dto.name,
                    edit_dto.file_location,
                    edit_dto.configured_interpreters
                )
                
                # Update the template data in the list
                templates_data[i] = {
                    'id': updated_template.id,
                    'name': updated_template.name,
                    'file_location': updated_template.file_location,
                    'interpreters': updated_template.interpreters
                }
                
                # Save updated list to file
                self._save_templates_to_file(templates_data)
                # Note: In a real implementation, don't forget to delete the old file if changing file_location.
                
                return updated_template
                
        # Template not found
        return None

    def delete_template(self, template_id):
        """
        Delete a template by its ID from file storage.

        Args:
            template_id (str): The ID of the template to delete

        Returns:
            bool: True if template was found and deleted, False otherwise
        """
        # Load templates from file
        templates_data = self._load_templates_from_file()
        
        # Find and remove the template
        for i, template_data in enumerate(templates_data):
            if template_data['id'] == template_id:
                del templates_data[i]
                # Save updated list to file
                self._save_templates_to_file(templates_data)
                return True
        return False

    def generate_new_id(self):
        """
        Generate a new unique ID for a template from file storage.

        Returns:
            str: A new unique ID
        """
        # Load templates from file
        templates_data = self._load_templates_from_file()
        
        # Simple implementation - find the highest numeric ID and add 1
        max_id = 0
        for template_data in templates_data:
            try:
                template_id_num = int(template_data['id'])
                if template_id_num > max_id:
                    max_id = template_id_num
            except ValueError:
                # Non-numeric ID, skip
                pass
        return str(max_id + 1)
    
    def _convert_data_to_template(self, template_data):
        """
        Convert a template data dictionary to a StudentDataSheetTemplate object.
        
        Args:
            template_data (dict): Dictionary containing template data
            
        Returns:
            StudentDataSheetTemplate: The converted template object
        """
        return StudentDataSheetTemplate(
            template_data['id'],
            template_data['name'],
            template_data['file_location'],
            template_data['interpreters']
        )
    
    def _ensure_storage_file_exists(self):
        """
        Ensure the storage file exists. If not, create an empty one.
        """
        if not os.path.exists(self.storage_file_path):
            self._save_templates_to_file([])
    
    def _load_templates_from_file(self):
        """
        Load templates data from the JSON storage file.
        
        Returns:
            list: List of template dictionaries
        """
        try:
            with open(self.storage_file_path, 'r', encoding='utf-8') as file:
                return json.load(file)
        except (FileNotFoundError, json.JSONDecodeError):
            return []
    
    def _save_templates_to_file(self, templates_data):
        """
        Save templates data to the JSON storage file.
        Creates parent directories if they don't exist.
        
        Args:
            templates_data (list): List of template dictionaries to save
        """
        # Create parent directories if they don't exist
        parent_dir = os.path.dirname(self.storage_file_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir, exist_ok=True)
        
        with open(self.storage_file_path, 'w', encoding='utf-8') as file:
            json.dump(templates_data, file, indent=2, ensure_ascii=True)